site_name: My Docs

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: blue

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
